# application.yml
# ???? ??
server:
  port: 8080

# ?? ANSI ??
spring:
  # thymeleaf ??
  thymeleaf:
    cache: false
    prefix: classpath:templates/

  # datasource ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbt4f1?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: chaiginmoo@gmail.com
    password: bepmiatesbamjbkw
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  output:
    ansi:
      enabled: always


#  # security
  security:
    user:
      name: user1     # ??? security username
      password: 1234   #  password
#
#    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: 1070300711196-91tkvq8rd1ga15ml4hof2e6qs3e0be8j.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
          naver:
            client-id: h7igRvKbwk1xsUAJwmNj
            client-secret: WMwLtGszgg
            client-authentication-method: client_secret_post
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id: 5f8ba70602f4a1771fd20b953c014bc5
            client-secret: mThM2irknfMl5eUwUWsY821fdM8mMJ3D
            client-authentication-method: client_secret_post
            scope:
            #              - account_email
            #              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: kakao
        #            client-authentication-method: POST
        #provider ??
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
#
# MyBatis ??(mapper) ?? ?? ??
# src/main/resources ??? ?? ??
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:
  upload:
    path: upload

#app:
#  # ?? ??? ??
#  upload:
#    path: upload
#
#  # ??? ?? ???
#  pagination:
#    write_pages: 10  # ?? write_pages ?. ? [???] ? ??? ???? ????
#    page_rows: 10   # ?? page_rows ?.  ? '???'? ??? ?? ??? ?????
#
#  # OAuth2
  oauth2:
    password: 1234
#
#    # Kakao ??? ?? ???
#    kakao:
#      client-id: 5f8ba70602f4a1771fd20b953c014bc5   # ? ?
#      redirect-uri: http://localhost:8080/oauth2/kakao/callback  # Redirect URI
#      token-uri: https://kauth.kakao.com/oauth/token   # access token ?? URI
#      user-info-uri: https://kapi.kakao.com/v2/user/me   # ??? profile ?? URI




